// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_static_objects.proto

#ifndef PROTOBUF_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto__INCLUDED
#define PROTOBUF_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace StaticObjectsProtobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
void protobuf_AssignDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();

class Point;
class Wall;
class StaticObjects;

// ===================================================================

class Point : public ::google::protobuf::Message {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  void Swap(Point* other);

  // implements Message ----------------------------------------------

  Point* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StaticObjectsProtobuf.Point)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();

  void InitAsDefaultInstance();
  static Point* default_instance_;
};
// -------------------------------------------------------------------

class Wall : public ::google::protobuf::Message {
 public:
  Wall();
  virtual ~Wall();

  Wall(const Wall& from);

  inline Wall& operator=(const Wall& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Wall& default_instance();

  void Swap(Wall* other);

  // implements Message ----------------------------------------------

  Wall* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Wall& from);
  void MergeFrom(const Wall& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .StaticObjectsProtobuf.Point beginning = 1;
  inline bool has_beginning() const;
  inline void clear_beginning();
  static const int kBeginningFieldNumber = 1;
  inline const ::StaticObjectsProtobuf::Point& beginning() const;
  inline ::StaticObjectsProtobuf::Point* mutable_beginning();
  inline ::StaticObjectsProtobuf::Point* release_beginning();
  inline void set_allocated_beginning(::StaticObjectsProtobuf::Point* beginning);

  // required .StaticObjectsProtobuf.Point end = 2;
  inline bool has_end() const;
  inline void clear_end();
  static const int kEndFieldNumber = 2;
  inline const ::StaticObjectsProtobuf::Point& end() const;
  inline ::StaticObjectsProtobuf::Point* mutable_end();
  inline ::StaticObjectsProtobuf::Point* release_end();
  inline void set_allocated_end(::StaticObjectsProtobuf::Point* end);

  // @@protoc_insertion_point(class_scope:StaticObjectsProtobuf.Wall)
 private:
  inline void set_has_beginning();
  inline void clear_has_beginning();
  inline void set_has_end();
  inline void clear_has_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::StaticObjectsProtobuf::Point* beginning_;
  ::StaticObjectsProtobuf::Point* end_;
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();

  void InitAsDefaultInstance();
  static Wall* default_instance_;
};
// -------------------------------------------------------------------

class StaticObjects : public ::google::protobuf::Message {
 public:
  StaticObjects();
  virtual ~StaticObjects();

  StaticObjects(const StaticObjects& from);

  inline StaticObjects& operator=(const StaticObjects& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StaticObjects& default_instance();

  void Swap(StaticObjects* other);

  // implements Message ----------------------------------------------

  StaticObjects* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StaticObjects& from);
  void MergeFrom(const StaticObjects& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StaticObjectsProtobuf.Wall walls = 1;
  inline int walls_size() const;
  inline void clear_walls();
  static const int kWallsFieldNumber = 1;
  inline const ::StaticObjectsProtobuf::Wall& walls(int index) const;
  inline ::StaticObjectsProtobuf::Wall* mutable_walls(int index);
  inline ::StaticObjectsProtobuf::Wall* add_walls();
  inline const ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Wall >&
      walls() const;
  inline ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Wall >*
      mutable_walls();

  // repeated .StaticObjectsProtobuf.Point points = 2;
  inline int points_size() const;
  inline void clear_points();
  static const int kPointsFieldNumber = 2;
  inline const ::StaticObjectsProtobuf::Point& points(int index) const;
  inline ::StaticObjectsProtobuf::Point* mutable_points(int index);
  inline ::StaticObjectsProtobuf::Point* add_points();
  inline const ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Point >&
      points() const;
  inline ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Point >*
      mutable_points();

  // @@protoc_insertion_point(class_scope:StaticObjectsProtobuf.StaticObjects)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Wall > walls_;
  ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Point > points_;
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto();

  void InitAsDefaultInstance();
  static StaticObjects* default_instance_;
};
// ===================================================================


// ===================================================================

// Point

// required int32 x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Point::x() const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.Point.x)
  return x_;
}
inline void Point::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:StaticObjectsProtobuf.Point.x)
}

// required int32 y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Point::y() const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.Point.y)
  return y_;
}
inline void Point::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:StaticObjectsProtobuf.Point.y)
}

// -------------------------------------------------------------------

// Wall

// required .StaticObjectsProtobuf.Point beginning = 1;
inline bool Wall::has_beginning() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Wall::set_has_beginning() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Wall::clear_has_beginning() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Wall::clear_beginning() {
  if (beginning_ != NULL) beginning_->::StaticObjectsProtobuf::Point::Clear();
  clear_has_beginning();
}
inline const ::StaticObjectsProtobuf::Point& Wall::beginning() const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.Wall.beginning)
  return beginning_ != NULL ? *beginning_ : *default_instance_->beginning_;
}
inline ::StaticObjectsProtobuf::Point* Wall::mutable_beginning() {
  set_has_beginning();
  if (beginning_ == NULL) beginning_ = new ::StaticObjectsProtobuf::Point;
  // @@protoc_insertion_point(field_mutable:StaticObjectsProtobuf.Wall.beginning)
  return beginning_;
}
inline ::StaticObjectsProtobuf::Point* Wall::release_beginning() {
  clear_has_beginning();
  ::StaticObjectsProtobuf::Point* temp = beginning_;
  beginning_ = NULL;
  return temp;
}
inline void Wall::set_allocated_beginning(::StaticObjectsProtobuf::Point* beginning) {
  delete beginning_;
  beginning_ = beginning;
  if (beginning) {
    set_has_beginning();
  } else {
    clear_has_beginning();
  }
  // @@protoc_insertion_point(field_set_allocated:StaticObjectsProtobuf.Wall.beginning)
}

// required .StaticObjectsProtobuf.Point end = 2;
inline bool Wall::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Wall::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Wall::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Wall::clear_end() {
  if (end_ != NULL) end_->::StaticObjectsProtobuf::Point::Clear();
  clear_has_end();
}
inline const ::StaticObjectsProtobuf::Point& Wall::end() const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.Wall.end)
  return end_ != NULL ? *end_ : *default_instance_->end_;
}
inline ::StaticObjectsProtobuf::Point* Wall::mutable_end() {
  set_has_end();
  if (end_ == NULL) end_ = new ::StaticObjectsProtobuf::Point;
  // @@protoc_insertion_point(field_mutable:StaticObjectsProtobuf.Wall.end)
  return end_;
}
inline ::StaticObjectsProtobuf::Point* Wall::release_end() {
  clear_has_end();
  ::StaticObjectsProtobuf::Point* temp = end_;
  end_ = NULL;
  return temp;
}
inline void Wall::set_allocated_end(::StaticObjectsProtobuf::Point* end) {
  delete end_;
  end_ = end;
  if (end) {
    set_has_end();
  } else {
    clear_has_end();
  }
  // @@protoc_insertion_point(field_set_allocated:StaticObjectsProtobuf.Wall.end)
}

// -------------------------------------------------------------------

// StaticObjects

// repeated .StaticObjectsProtobuf.Wall walls = 1;
inline int StaticObjects::walls_size() const {
  return walls_.size();
}
inline void StaticObjects::clear_walls() {
  walls_.Clear();
}
inline const ::StaticObjectsProtobuf::Wall& StaticObjects::walls(int index) const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.StaticObjects.walls)
  return walls_.Get(index);
}
inline ::StaticObjectsProtobuf::Wall* StaticObjects::mutable_walls(int index) {
  // @@protoc_insertion_point(field_mutable:StaticObjectsProtobuf.StaticObjects.walls)
  return walls_.Mutable(index);
}
inline ::StaticObjectsProtobuf::Wall* StaticObjects::add_walls() {
  // @@protoc_insertion_point(field_add:StaticObjectsProtobuf.StaticObjects.walls)
  return walls_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Wall >&
StaticObjects::walls() const {
  // @@protoc_insertion_point(field_list:StaticObjectsProtobuf.StaticObjects.walls)
  return walls_;
}
inline ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Wall >*
StaticObjects::mutable_walls() {
  // @@protoc_insertion_point(field_mutable_list:StaticObjectsProtobuf.StaticObjects.walls)
  return &walls_;
}

// repeated .StaticObjectsProtobuf.Point points = 2;
inline int StaticObjects::points_size() const {
  return points_.size();
}
inline void StaticObjects::clear_points() {
  points_.Clear();
}
inline const ::StaticObjectsProtobuf::Point& StaticObjects::points(int index) const {
  // @@protoc_insertion_point(field_get:StaticObjectsProtobuf.StaticObjects.points)
  return points_.Get(index);
}
inline ::StaticObjectsProtobuf::Point* StaticObjects::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:StaticObjectsProtobuf.StaticObjects.points)
  return points_.Mutable(index);
}
inline ::StaticObjectsProtobuf::Point* StaticObjects::add_points() {
  // @@protoc_insertion_point(field_add:StaticObjectsProtobuf.StaticObjects.points)
  return points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Point >&
StaticObjects::points() const {
  // @@protoc_insertion_point(field_list:StaticObjectsProtobuf.StaticObjects.points)
  return points_;
}
inline ::google::protobuf::RepeatedPtrField< ::StaticObjectsProtobuf::Point >*
StaticObjects::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:StaticObjectsProtobuf.StaticObjects.points)
  return &points_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace StaticObjectsProtobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5frobocup_5fssl_5fstatic_5fobjects_2eproto__INCLUDED
